/**
 * RecipeScreen Component V2
 * Displays recipe with interactive checklist — no emojis, Poppins font, new palette
 */

import React, { useState } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  Share,
  Alert,
  SafeAreaView,
  ActivityIndicator,
} from 'react-native';
import { theme } from '../theme';
import { apiService } from '../services/apiService';
import { useAuth } from '../contexts/AuthContext';

interface Recipe {
  name: string;
  ingredients: string[];
  steps: string[];
  time?: number;
}

interface RecipeScreenProps {
  navigation: any;
  route: {
    params: {
      recipe: Recipe;
    };
  };
}

export const RecipeScreen: React.FC<RecipeScreenProps> = ({ navigation, route }) => {
  const recipe = route.params?.recipe;
  const { user } = useAuth();
  const [checkedSteps, setCheckedSteps] = useState<{ [key: number]: boolean }>({});
  const [checkedIngredients, setCheckedIngredients] = useState<{ [key: number]: boolean }>({});
  const [isSaving, setIsSaving] = useState(false);
  const [isFavoriting, setIsFavoriting] = useState(false);

  if (!recipe) {
    return (
      <SafeAreaView style={styles.container}>
        <View style={styles.centeredContainer}>
          <Text style={styles.errorText}>No Recipe Found</Text>
          <TouchableOpacity style={styles.primaryButton} onPress={() => navigation.goBack()}>
            <Text style={styles.primaryButtonText}>Go Back</Text>
          </TouchableOpacity>
        </View>
      </SafeAreaView>
    );
  }

  const handleSave = async () => {
    setIsSaving(true);
    try {
      await apiService.saveRecipe(recipe);
      Alert.alert('Success', 'Recipe saved successfully!');
    } catch (error) {
      Alert.alert('Error', error instanceof Error ? error.message : 'Failed to save recipe');
    } finally {
      setIsSaving(false);
    }
  };

  const handleFavorite = async () => {
    if (!user) {
      Alert.alert('Authentication Required', 'Please sign in to favorite recipes.');
      return;
    }
    
    setIsFavoriting(true);
    try {
      await apiService.favoriteRecipe(user.id, recipe);
      Alert.alert('Success', 'Recipe added to favorites!');
    } catch (error) {
      Alert.alert('Error', error instanceof Error ? error.message : 'Failed to favorite recipe');
    } finally {
      setIsFavoriting(false);
    }
  };

  const toggleStepCheck = (index: number) => {
    setCheckedSteps((prev) => ({ ...prev, [index]: !prev[index] }));
  };

  const toggleIngredientCheck = (index: number) => {
    setCheckedIngredients((prev) => ({ ...prev, [index]: !prev[index] }));
  };

  const handleShare = async () => {
    try {
      const recipeText = formatRecipeForSharing();
      await Share.share({
        message: recipeText,
        title: `Recipe: ${recipe.name}`,
      });
    } catch (error) {
      Alert.alert('Error', 'Failed to share recipe');
    }
  };

  const formatRecipeForSharing = () => {
    const ingredientsList = recipe.ingredients.join('\n- ');
    const stepsList = recipe.steps.map((step, i) => `${i + 1}. ${step}`).join('\n');
    const timeText = recipe.time ? `\nTime: ${recipe.time} mins` : '';
    return `${recipe.name}${timeText}\n\nIngredients:\n- ${ingredientsList}\n\nSteps:\n${stepsList}\n\nGenerated by Meal Maker`;
  };

  const allIngredientsChecked =
    recipe.ingredients.length > 0 &&
    recipe.ingredients.every((_, i) => checkedIngredients[i]);
  const allStepsChecked =
    recipe.steps.length > 0 && recipe.steps.every((_, i) => checkedSteps[i]);

  return (
    <SafeAreaView style={styles.container}>
      <ScrollView contentContainerStyle={styles.contentContainer}>
        {/* Recipe Header */}
        <View style={styles.header}>
          <Text style={styles.recipeName}>{recipe.name}</Text>
          <View style={styles.headerInfo}>
            <Text style={styles.headerSubtitle}>Ready to cook</Text>
            {recipe.time && (
              <Text style={styles.timeBadge}>{recipe.time} mins</Text>
            )}
          </View>
        </View>

        {/* Ingredients Section */}
        <View style={styles.section}>
          <View style={styles.sectionHeader}>
            <Text style={styles.sectionTitle}>Ingredients</Text>
            {allIngredientsChecked && recipe.ingredients.length > 0 && (
              <View style={styles.completeBadge}>
                <Text style={styles.completeBadgeText}>All set</Text>
              </View>
            )}
          </View>

          <View style={styles.ingredientsList}>
            {recipe.ingredients.length > 0 ? (
              recipe.ingredients.map((ingredient, index) => (
                <TouchableOpacity
                  key={index}
                  style={styles.ingredientItem}
                  onPress={() => toggleIngredientCheck(index)}
                >
                  <View
                    style={[
                      styles.checkbox,
                      checkedIngredients[index] && styles.checkboxChecked,
                    ]}
                  >
                    {checkedIngredients[index] && (
                      <Text style={styles.checkboxText}>✓</Text>
                    )}
                  </View>
                  <Text
                    style={[
                      styles.ingredientText,
                      checkedIngredients[index] && styles.checkedText,
                    ]}
                  >
                    {ingredient}
                  </Text>
                </TouchableOpacity>
              ))
            ) : (
              <Text style={styles.emptyText}>No ingredients listed</Text>
            )}
          </View>
        </View>

        {/* Steps Section */}
        <View style={styles.section}>
          <View style={styles.sectionHeader}>
            <Text style={styles.sectionTitle}>Cooking Steps</Text>
            {allStepsChecked && recipe.steps.length > 0 && (
              <View style={styles.completeBadge}>
                <Text style={styles.completeBadgeText}>Done</Text>
              </View>
            )}
          </View>

          <View style={styles.stepsList}>
            {recipe.steps.length > 0 ? (
              recipe.steps.map((step, index) => (
                <TouchableOpacity
                  key={index}
                  style={styles.stepItem}
                  onPress={() => toggleStepCheck(index)}
                >
                  <View style={styles.stepNumber}>
                    <Text style={styles.stepNumberText}>{index + 1}</Text>
                  </View>
                  <View style={styles.stepContent}>
                    <Text
                      style={[
                        styles.stepText,
                        checkedSteps[index] && styles.checkedText,
                      ]}
                    >
                      {step}
                    </Text>
                    {checkedSteps[index] && (
                      <Text style={styles.stepCheckmark}>✓</Text>
                    )}
                  </View>
                </TouchableOpacity>
              ))
            ) : (
              <Text style={styles.emptyText}>No steps listed</Text>
            )}
          </View>
        </View>

        {/* Action Buttons */}
        <View style={styles.buttonContainer}>
          <TouchableOpacity
            style={[styles.favoriteButton, isFavoriting && styles.disabledButton]}
            onPress={handleFavorite}
            disabled={isFavoriting}
          >
            {isFavoriting ? (
              <ActivityIndicator color={theme.colors.buttonText} />
            ) : (
              <Text style={styles.favoriteButtonText}>Favorite Recipe</Text>
            )}
          </TouchableOpacity>

          <TouchableOpacity
            style={[styles.saveButton, isSaving && styles.disabledButton]}
            onPress={handleSave}
            disabled={isSaving}
          >
            {isSaving ? (
              <ActivityIndicator color={theme.colors.buttonText} />
            ) : (
              <Text style={styles.saveButtonText}>Save Recipe</Text>
            )}
          </TouchableOpacity>

          <TouchableOpacity style={styles.secondaryButton} onPress={handleShare}>
            <Text style={styles.secondaryButtonText}>Share Recipe</Text>
          </TouchableOpacity>

          <TouchableOpacity
            style={styles.primaryButton}
            onPress={() => navigation.navigate('Camera')}
          >
            <Text style={styles.primaryButtonText}>Try Another Recipe</Text>
          </TouchableOpacity>
        </View>

        {/* Progress Indicator */}
        <View style={styles.progressContainer}>
          <Text style={styles.progressText}>
            Progress: {Object.values(checkedSteps).filter(Boolean).length}/{recipe.steps.length} steps completed
          </Text>
          <View style={styles.progressBar}>
            <View
              style={[
                styles.progressFill,
                {
                  width: `${
                    recipe.steps.length > 0
                      ? (Object.values(checkedSteps).filter(Boolean).length /
                          recipe.steps.length) *
                        100
                      : 0
                  }%`,
                },
              ]}
            />
          </View>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  centeredContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: theme.spacing.xl,
  },
  errorText: {
    fontFamily: theme.typography.fontFamily.semibold,
    fontSize: theme.typography.fontSize.lg,
    color: theme.colors.error,
    marginBottom: theme.spacing.lg,
  },
  contentContainer: {
    paddingBottom: theme.spacing.xxl,
  },
  header: {
    padding: theme.spacing.xl,
    backgroundColor: theme.colors.surfaceSolid,
    marginBottom: theme.spacing.lg,
  },
  recipeName: {
    fontFamily: theme.typography.fontFamily.bold,
    fontSize: theme.typography.fontSize['3xl'],
    color: theme.colors.text,
    marginBottom: theme.spacing.sm,
  },
  headerSubtitle: {
    fontFamily: theme.typography.fontFamily.regular,
    fontSize: theme.typography.fontSize.base,
    color: theme.colors.textMuted,
  },
  headerInfo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  timeBadge: {
    fontFamily: theme.typography.fontFamily.semibold,
    fontSize: theme.typography.fontSize.sm,
    color: theme.colors.text,
    backgroundColor: theme.colors.surfaceLight,
    paddingHorizontal: theme.spacing.sm,
    paddingVertical: theme.spacing.xs,
    borderRadius: theme.borderRadius.sm,
  },
  section: {
    marginBottom: theme.spacing.xl,
    paddingHorizontal: theme.spacing.xl,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: theme.spacing.md,
  },
  sectionTitle: {
    fontFamily: theme.typography.fontFamily.bold,
    fontSize: theme.typography.fontSize.xl,
    color: theme.colors.text,
  },
  completeBadge: {
    backgroundColor: theme.colors.success,
    paddingVertical: theme.spacing.xs,
    paddingHorizontal: theme.spacing.sm,
    borderRadius: theme.borderRadius.full,
    overflow: 'hidden',
  },
  completeBadgeText: {
    fontFamily: theme.typography.fontFamily.semibold,
    fontSize: theme.typography.fontSize.sm,
    color: theme.colors.background,
  },
  ingredientsList: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.borderRadius.lg,
    padding: theme.spacing.md,
  },
  ingredientItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: theme.spacing.md,
    paddingHorizontal: theme.spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.divider,
  },
  ingredientText: {
    fontFamily: theme.typography.fontFamily.regular,
    fontSize: theme.typography.fontSize.base,
    color: theme.colors.text,
    flex: 1,
    marginLeft: theme.spacing.md,
  },
  stepsList: {
    gap: theme.spacing.md,
  },
  stepItem: {
    flexDirection: 'row',
    backgroundColor: theme.colors.surface,
    borderRadius: theme.borderRadius.lg,
    padding: theme.spacing.md,
    alignItems: 'flex-start',
  },
  stepNumber: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: theme.colors.button,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: theme.spacing.md,
  },
  stepNumberText: {
    fontFamily: theme.typography.fontFamily.bold,
    color: theme.colors.buttonText,
    fontSize: theme.typography.fontSize.base,
  },
  stepContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  stepText: {
    fontFamily: theme.typography.fontFamily.regular,
    flex: 1,
    fontSize: theme.typography.fontSize.base,
    color: theme.colors.text,
    lineHeight: 24,
  },
  stepCheckmark: {
    fontFamily: theme.typography.fontFamily.bold,
    fontSize: theme.typography.fontSize.xl,
    color: theme.colors.success,
    marginLeft: theme.spacing.md,
  },
  checkedText: {
    textDecorationLine: 'line-through',
    color: theme.colors.textMuted,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: theme.borderRadius.md,
    borderWidth: 2,
    borderColor: theme.colors.text,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkboxChecked: {
    backgroundColor: theme.colors.button,
    borderColor: theme.colors.button,
  },
  checkboxText: {
    fontFamily: theme.typography.fontFamily.bold,
    color: theme.colors.buttonText,
  },
  emptyText: {
    fontFamily: theme.typography.fontFamily.regular,
    color: theme.colors.textMuted,
    fontSize: theme.typography.fontSize.base,
    textAlign: 'center',
    paddingVertical: theme.spacing.lg,
  },
  buttonContainer: {
    paddingHorizontal: theme.spacing.xl,
    gap: theme.spacing.md,
    marginBottom: theme.spacing.xl,
  },
  primaryButton: {
    backgroundColor: theme.colors.button,
    paddingVertical: theme.spacing.lg,
    paddingHorizontal: theme.spacing.xl,
    borderRadius: theme.borderRadius.xl,
    alignItems: 'center',
    ...theme.shadow.md,
  },
  primaryButtonText: {
    fontFamily: theme.typography.fontFamily.semibold,
    color: theme.colors.buttonText,
    fontSize: theme.typography.fontSize.lg,
  },
  favoriteButton: {
    backgroundColor: '#FF6B6B', // A nice red/pink for favorites
    paddingVertical: theme.spacing.lg,
    paddingHorizontal: theme.spacing.xl,
    borderRadius: theme.borderRadius.xl,
    alignItems: 'center',
    marginBottom: theme.spacing.xs,
    ...theme.shadow.md,
  },
  favoriteButtonText: {
    fontFamily: theme.typography.fontFamily.semibold,
    color: theme.colors.buttonText,
    fontSize: theme.typography.fontSize.lg,
  },
  saveButton: {
    backgroundColor: theme.colors.button,
    paddingVertical: theme.spacing.lg,
    paddingHorizontal: theme.spacing.xl,
    borderRadius: theme.borderRadius.xl,
    alignItems: 'center',
    marginBottom: theme.spacing.xs,
    ...theme.shadow.md,
  },
  saveButtonText: {
    fontFamily: theme.typography.fontFamily.semibold,
    color: theme.colors.buttonText,
    fontSize: theme.typography.fontSize.lg,
  },
  disabledButton: {
    opacity: 0.6,
  },
  secondaryButton: {
    backgroundColor: theme.colors.surfaceLight,
    paddingVertical: theme.spacing.md,
    paddingHorizontal: theme.spacing.lg,
    borderRadius: theme.borderRadius.lg,
    alignItems: 'center',
  },
  secondaryButtonText: {
    fontFamily: theme.typography.fontFamily.medium,
    color: theme.colors.text,
    fontSize: theme.typography.fontSize.base,
  },
  progressContainer: {
    paddingHorizontal: theme.spacing.xl,
    paddingVertical: theme.spacing.md,
    backgroundColor: theme.colors.surface,
    marginHorizontal: theme.spacing.xl,
    borderRadius: theme.borderRadius.lg,
  },
  progressText: {
    fontFamily: theme.typography.fontFamily.regular,
    fontSize: theme.typography.fontSize.sm,
    color: theme.colors.textMuted,
    marginBottom: theme.spacing.sm,
  },
  progressBar: {
    height: 8,
    backgroundColor: theme.colors.divider,
    borderRadius: theme.borderRadius.full,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: theme.colors.success,
    borderRadius: theme.borderRadius.full,
  },
});
